#17[Feature] Add option to generate multiple stories #17
eduardconstantin/storybook-genie pull request #30
Opened 2024-10-03 06:06 UTC by Ananta2003

In this commit, we implemented a feature that allows users to generate multiple stories. The following changes were made:

1. Submission Button: A new submission button was created, enabling users to initiate the story generation process seamlessly.
2. Multiple Selection Option: Introduced a multiple select option, allowing users to choose several stories at once for generation. This enhances user flexibility and customization.
3. User Interface Update: The user interface was updated to incorporate the new button and multiple selection feature, ensuring a smooth and intuitive user experience.

Please note that my OpenAI access has expired, so I couldn't actually run the code, but the features were running fine during development. If the implementation doesn't work as expected, feel free to ask for changes. If it does work, feel free to commit the code!

![Screenshot 2024-10-03 113411](https://github.com/user-attachments/assets/456b2485-4c0f-4b7c-b656-1f9349f59aec)

2024-10-03 16:52 UTC, eduardconstantin requested changes
I can't check the code generation yet but this mostly looks good, just a few things that are not quite right:
- the folders are not highlighted in blue (see pucture)
![image](https://github.com/user-attachments/assets/270b2cc3-4b34-4763-918c-c34e5f0e838f)
- when I select a folder the arrow disappears and it appears after I press up or down, the first file or folder inside that folder should be highlighted

2024-10-04 07:21 UTC, Ananta2003 commented
In the UI, the arrow is initially hidden, but it becomes visible when navigating. Could you please provide more details regarding the remaining issues?

2024-10-04 08:52 UTC, eduardconstantin commented
> In the UI, the arrow is initially hidden, but it becomes visible when navigating. Could you please provide more details regarding the remaining issues?

That's the issue, the arrow should not be hidden

2024-10-04 16:28 UTC, eduardconstantin requested changes
I put suggestions in the code.

2024-10-04 16:28 UTC, eduardconstantin commented on package.json
> +    "chalk": "^5.3.0",
we don't need this package
```suggestion
```

2024-10-04 16:28 UTC, eduardconstantin commented on src/converter.js
> +  for (const component of components) {
in index.js you are sending the files one by one in the forEach loop, there is no need for this for loop here

2024-10-04 16:28 UTC, eduardconstantin commented on src/selector.js
> +  const [cursorPosition, setCursorPos] = useState(0);
The initial index should be 1
```suggestion
  const [cursorPosition, setCursorPos] = useState(1);
```

2024-10-04 16:28 UTC, eduardconstantin commented on src/selector.js
> +  const resetCursorToFirstSelectable = (files) => {
You can remove this function

2024-10-04 16:28 UTC, eduardconstantin commented on src/selector.js
> +        const displayText = isDirectory ? `\x1b[94m\x1b[1m[DIR]${file}\x1b[0m ` : file;
```suggestion
        const displayText = isDirectory ? `\x1b[94m\x1b[1m[DIR]\x1b[0m ${file}` : file;
```

2024-10-04 16:28 UTC, eduardconstantin commented on src/selector.js
> +      return `${selectedMarker}\x1b[36m❯ ${line}\x1b[0m`;
```suggestion
      return line.split(" ").length === 2
        ? `${selectedMarker}\x1b[36m❯ ${line.split(" ")[0]}\x1b[0m \x1b[36m${line.split(" ")[1]}\x1b[0m`
        : `${selectedMarker}\x1b[36m❯ ${line}\x1b[0m`;
```

2024-10-04 16:28 UTC, eduardconstantin commented on src/selector.js
> +  const goBackOption = { name: `\x1b[90m[..]  BACK\x1b[0m`, value: "..", isDirectory: true };
```suggestion
  const goBackOption = { name: `\x1b[90m[..]  BACK\x1b[0m`, value: "..", isDirectory: false};
```

2024-10-04 16:28 UTC, eduardconstantin commented on src/converter.js
> +export async function componentConverter(components, model, template) {
```suggestion
export async function componentConverter(component, model, template) {
```

2024-10-04 17:35 UTC, Ananta2003 commented
Hi @eduardconstantin ,

Thank you for your suggestions! I’ve committed the changes and updated my PR. Please verify when you get the chance.

I also want to thank you for the updates and guidance throughout this process—it has helped me learn a lot.

2024-10-04 18:40 UTC, eduardconstantin approved these changes
Lovely! Thank you for your help!

2024-10-04 18:40 UTC, merged